/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#48e4da",
        "on-secondary-fixed-variant": "#920091",
        "primary-dim": "#9c42f4",
        "on-tertiary": "#006963",
        "secondary-container": "#a900a9",
        "on-tertiary-fixed-variant": "#006b65",
        "error": "#ff6e84",
        "surface-tint": "#ca98ff",
        "inverse-primary": "#8523dd",
        "tertiary": "#d4fffa",
        "primary-container": "#c185ff",
        "tertiary-fixed": "#69fff3",
        "tertiary-fixed-dim": "#57f0e5",
        "on-secondary": "#400040",
        "background": "#0d0e12",
        "surface": "#0d0e12",
        "secondary": "#ff51fa",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#69fff3",
        "on-error-container": "#ffb2b9",
        "secondary-fixed-dim": "#ffa6f3",
        "surface-dim": "#0d0e12",
        "on-background": "#faf8fe",
        "surface-container-high": "#1e1f25",
        "secondary-dim": "#ff51fa",
        "surface-variant": "#24252b",
        "on-surface": "#faf8fe",
        "inverse-surface": "#faf8fe",
        "error-container": "#a70138",
        "surface-bright": "#2a2c32",
        "primary-fixed": "#c185ff",
        "on-surface-variant": "#abaab0",
        "inverse-on-surface": "#54555a",
        "primary": "#ca98ff",
        "on-primary-fixed-variant": "#420078",
        "on-tertiary-fixed": "#004c47",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#350062",
        "outline": "#75757a",
        "primary-fixed-dim": "#b772ff",
        "surface-container-highest": "#24252b",
        "error-dim": "#d73357",
        "on-tertiary-container": "#00605b",
        "surface-container-low": "#121318",
        "secondary-fixed": "#ffbdf3",
        "outline-variant": "#47484c",
        "surface-container": "#18191e",
        "on-primary": "#46007d",
        "on-secondary-fixed": "#620061",
        "on-error": "#490013",
        "on-secondary-container": "#fff5f9"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
